use std::fmt::{Display, Formatter};

/// The 52 blendshape coefficients.
#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Hash, Copy, Clone)]
#[repr(C)]
pub enum FaceLandmarkBlendshapes {
    Neutral = 0,
    BrowDownLeft = 1,
    BrowDownRight = 2,
    BrowInnerUp = 3,
    BrowOuterUpLeft = 4,
    BrowOuterUpRight = 5,
    CheekPuff = 6,
    CheekSquintLeft = 7,
    CheekSquintRight = 8,
    EyeBlinkLeft = 9,
    EyeBlinkRight = 10,
    EyeLookDownLeft = 11,
    EyeLookDownRight = 12,
    EyeLookInLeft = 13,
    EyeLookInRight = 14,
    EyeLookOutLeft = 15,
    EyeLookOutRight = 16,
    EyeLookUpLeft = 17,
    EyeLookUpRight = 18,
    EyeSquintLeft = 19,
    EyeSquintRight = 20,
    EyeWideLeft = 21,
    EyeWideRight = 22,
    JawForward = 23,
    JawLeft = 24,
    JawOpen = 25,
    JawRight = 26,
    MouthClose = 27,
    MouthDimpleLeft = 28,
    MouthDimpleRight = 29,
    MouthFrownLeft = 30,
    MouthFrownRight = 31,
    MouthFunnel = 32,
    MouthLeft = 33,
    MouthLowerDownLeft = 34,
    MouthLowerDownRight = 35,
    MouthPressLeft = 36,
    MouthPressRight = 37,
    MouthPucker = 38,
    MouthRight = 39,
    MouthRollLower = 40,
    MouthRollUpper = 41,
    MouthShrugLower = 42,
    MouthShrugUpper = 43,
    MouthSmileLeft = 44,
    MouthSmileRight = 45,
    MouthStretchLeft = 46,
    MouthStretchRight = 47,
    MouthUpperUpLeft = 48,
    MouthUpperUpRight = 49,
    NoseSneerLeft = 50,
    NoseSneerRight = 51,
}

impl FaceLandmarkBlendshapes {
    pub const NAMES: &'static [&'static str] = &[
        "NEUTRAL",
        "BROW_DOWN_LEFT",
        "BROW_DOWN_RIGHT",
        "BROW_INNER_UP",
        "BROW_OUTER_UP_LEFT",
        "BROW_OUTER_UP_RIGHT",
        "CHEEK_PUFF",
        "CHEEK_SQUINT_LEFT",
        "CHEEK_SQUINT_RIGHT",
        "EYE_BLINK_LEFT",
        "EYE_BLINK_RIGHT",
        "EYE_LOOK_DOWN_LEFT",
        "EYE_LOOK_DOWN_RIGHT",
        "EYE_LOOK_IN_LEFT",
        "EYE_LOOK_IN_RIGHT",
        "EYE_LOOK_OUT_LEFT",
        "EYE_LOOK_OUT_RIGHT",
        "EYE_LOOK_UP_LEFT",
        "EYE_LOOK_UP_RIGHT",
        "EYE_SQUINT_LEFT",
        "EYE_SQUINT_RIGHT",
        "EYE_WIDE_LEFT",
        "EYE_WIDE_RIGHT",
        "JAW_FORWARD",
        "JAW_LEFT",
        "JAW_OPEN",
        "JAW_RIGHT",
        "MOUTH_CLOSE",
        "MOUTH_DIMPLE_LEFT",
        "MOUTH_DIMPLE_RIGHT",
        "MOUTH_FROWN_LEFT",
        "MOUTH_FROWN_RIGHT",
        "MOUTH_FUNNEL",
        "MOUTH_LEFT",
        "MOUTH_LOWER_DOWN_LEFT",
        "MOUTH_LOWER_DOWN_RIGHT",
        "MOUTH_PRESS_LEFT",
        "MOUTH_PRESS_RIGHT",
        "MOUTH_PUCKER",
        "MOUTH_RIGHT",
        "MOUTH_ROLL_LOWER",
        "MOUTH_ROLL_UPPER",
        "MOUTH_SHRUG_LOWER",
        "MOUTH_SHRUG_UPPER",
        "MOUTH_SMILE_LEFT",
        "MOUTH_SMILE_RIGHT",
        "MOUTH_STRETCH_LEFT",
        "MOUTH_STRETCH_RIGHT",
        "MOUTH_UPPER_UP_LEFT",
        "MOUTH_UPPER_UP_RIGHT",
        "NOSE_SNEER_LEFT",
        "NOSE_SNEER_RIGHT",
    ];

    #[inline(always)]
    pub fn name(&self) -> &'static str {
        Self::NAMES[(*self) as u32 as usize]
    }
}

impl Display for FaceLandmarkBlendshapes {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
